import "./globals.css";
import { Antic_Didone } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const antic = Antic_Didone({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={antic.className}>{children}</body>
    </html>
  );
}
